/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Footer: typeof import('./components/Footer.vue')['default']
    Game: typeof import('./components/home/Game.vue')['default']
    GameBattle: typeof import('./components/GameBattle.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Index: typeof import('./components/news/Index.vue')['default']
    Layout: typeof import('./components/home/Layout.vue')['default']
    Loding: typeof import('./components/Loding.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Main: typeof import('./components/join/Main.vue')['default']
    News: typeof import('./components/home/News.vue')['default']
    RoomSelector: typeof import('./components/RoomSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotMachine: typeof import('./components/SlotMachine.vue')['default']
    Swiper: typeof import('./components/home/Swiper.vue')['default']
  }
}
